---
extends: relaxed

rules:
  line-length: disable
  trailing-spaces: disable
  new-line-at-end-of-file: disable
  indentation: disable
  key-duplicates: disable
  empty-lines: disable
  colons: disable
  commas: disable
